#%RAML 0.8
title: Email API 
version: 1.0
baseUri: http://pinnacol.com/api/email/{version}
protocols:  [ HTTP, HTTPS ]

/testsend:
  displayName: resourceName
  
  post:
    body:
      application/json:      
        example: |
          {
            "to": "zed@pinnacol.com",
            "subject":"test subject"
          }
          
/testsendform:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          to:
            description: the email that the person/group is going to.
            type: string
            required: true
            example: email@emailexample.com
            
          subject:
            description: subject of the email.
            type: string
            required: true
            example: test subject
          body:
            description: body of the email
            type: string
            required: false
            
            
/testsendformMultiPart:
    post:
      body:
          multipart/form-data:
            formParameters:
              to:
                description: the intended recipient
                required: false
                example: email@emailexample.com
        
          